apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-cluster/bgd
spec:
  destination:
    namespace: bgd
    name: local-cluster
  source:
    path: apps/base
    repoURL: https://github.com/gitops-examples/openshift-gitops-agent
    targetRevision: HEAD
  project: local-cluster
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
